import asyncio
import importlib.util
import json
import os
from contextlib import asynccontextmanager

import httpx
from fastapi import FastAPI, WebSocket
from fastapi.middleware.cors import CORSMiddleware

from pipeline import local_ollama_url, run_pipeline
from session import register, cancel, cleanup_done
from state import get_state, set_state, remove_state
from stt import _load_model as load_stt
from tts import _load_piper as load_tts, _model_path as tts_model_path

# Token is generated by the Tauri sidecar launcher (voice_sidecar.rs) and
# passed via VOICE_OS_TOKEN. If the variable is absent the endpoint is
# effectively unprotected, so we fail closed: a missing/empty token means
# every WebSocket connection is rejected.
_VOICE_TOKEN: str | None = os.environ.get("VOICE_OS_TOKEN") or None


@asynccontextmanager
async def lifespan(app: FastAPI):
    # Preload models at startup so first request isn't slow
    load_stt()
    load_tts()
    yield
    cleanup_done()


app = FastAPI(lifespan=lifespan)

app.add_middleware(
    CORSMiddleware,
    # Voice OS does not use browser cookies or HTTP authentication. WebSocket
    # authorization is handled separately, so wildcard origins are safe only
    # with credentials disabled.
    allow_origins=["*"],
    allow_credentials=False,
    allow_methods=["*"],
    allow_headers=["*"],
)


@app.get("/health")
async def health():
    # The production sidecar stores Piper under VOICE_PIPER_MODEL_DIR (the
    # Runtime Hub directory), not next to this bundled backend. Report the
    # actual model location so desktop health reflects a usable local TTS.
    tts_ok = False
    try:
        tts_ok = tts_model_path().exists()
    except Exception:
        pass
    ollama_reachable = False
    try:
        async with httpx.AsyncClient(timeout=2.0) as client:
            response = await client.get(local_ollama_url().removesuffix("/api/chat") + "/api/tags")
            ollama_reachable = response.is_success
    except Exception:
        pass
    return {
        "status": "ok",
        "stt": importlib.util.find_spec("faster_whisper") is not None,
        "tts": tts_ok and importlib.util.find_spec("piper") is not None,
        "ollama": {"url": local_ollama_url(), "reachable": ollama_reachable},
    }


@app.websocket("/ws")
async def ws_endpoint(ws: WebSocket):
    # Accept the WebSocket handshake first — close codes (1008) can only be
    # sent after the HTTP→WS upgrade completes. Token validation follows
    # immediately; unauthenticated connections are closed before any data flows.
    await ws.accept()
    provided = ws.query_params.get("token")
    if _VOICE_TOKEN is None or provided != _VOICE_TOKEN:
        await ws.close(code=1008)  # 1008 = Policy Violation
        return
    session_id = ws.headers.get("x-session", "anon")
    set_state(session_id, "idle")

    buffer = bytearray()
    conversation_history: list[dict] = []

    async def process(pcm: bytes) -> None:
        async for event in run_pipeline(session_id, pcm, conversation_history):
            etype = event.get("type")
            try:
                if etype == "tts":
                    await ws.send_bytes(event["audio"])
                else:
                    await ws.send_json(event)
            except Exception:
                return

            if etype == "state":
                set_state(session_id, event["value"])

            if etype == "stt":
                conversation_history.append({"role": "user", "content": event["text"]})

            if etype == "llm" and event.get("done"):
                reply = event.get("full_reply", "")
                if reply:
                    conversation_history.append({"role": "assistant", "content": reply})
                if len(conversation_history) > 20:
                    conversation_history[:] = conversation_history[-20:]

    try:
        while True:
            msg = await ws.receive()

            if "bytes" in msg:
                # Barge-in: cancel current task when assistant is speaking
                if get_state(session_id) == "speaking":
                    cancel(session_id)
                    set_state(session_id, "idle")
                    buffer = bytearray()

                buffer.extend(msg["bytes"])

                if len(buffer) >= 24000:  # ~1.5s of 16kHz 16-bit mono PCM
                    data = bytes(buffer)
                    buffer = bytearray()
                    task = asyncio.create_task(process(data))
                    register(session_id, task)

            elif "text" in msg:
                try:
                    ctrl = json.loads(msg["text"])
                    if ctrl.get("type") == "reset":
                        cancel(session_id)
                        conversation_history.clear()
                        buffer = bytearray()
                        set_state(session_id, "idle")
                        await ws.send_json({"type": "state", "value": "idle"})
                except Exception:
                    pass

    finally:
        cancel(session_id)
        remove_state(session_id)
        cleanup_done()
