import { createAgentOutput, AgentOutputTypes } from '../../agents/shared/agentOutputSchemas';
import { createDiffProposal } from './diffProposalService';
import { appendTraceEvent } from './traceabilityService';
import { canExecuteAction, getExecutionApprovalState, getAgentMode, AGENT_MODES } from './executionModeService';
import { createApprovalRequest } from '../approval/approvalService';
import { addFailureMemory, addMemoryItem } from '../memory/ecosystemMemoryService';
import { createWorkContractDraft } from './workContractService';
import { createDefaultCrossVerificationChain } from './verificationChainService';
import { buildAgentScopedContexts } from './contextEngineeringService';
import { createProjectDNA } from '../projectExecution/projectDnaService';
import { evaluateAiReviewRequirement } from './aiReviewPolicyService';
import {
  createJoseCoordinationReport,
  produceApprovalGates,
  produceExecutionSequence,
  receiveProjectIntake,
  routeProjectTasks
} from './joseOrchestrationService';

function deterministicAgentTemplate(agentId, taskPacket, projectName) {
  const base = {
    agentId,
    projectId: taskPacket.projectId,
    title: `${agentId} output: ${taskPacket.title}`,
    status: 'ready',
    confidence: 'inferred',
    riskLevel: taskPacket.riskLevel || 'medium',
    assumptions: ['Generated by deterministic local template'],
    verifiedFacts: [`Task packet received for ${projectName}`],
    openQuestions: [],
    recommendedNextSteps: ['Review and approve before execution'],
    requiresApproval: Boolean(taskPacket.requiresApproval),
    relatedFiles: [],
    proposedChanges: []
  };

  if (agentId === 'maria') return createAgentOutput(AgentOutputTypes.PROJECT_BREAKDOWN, { ...base, summary: 'Requirements, roadmap, and backlog draft prepared.' });
  if (agentId === 'hector') return createAgentOutput(AgentOutputTypes.RESEARCH_REPORT, { ...base, summary: 'Research checklist created. Live sources are not queried in local-only mode.' });
  if (agentId === 'miya') return createAgentOutput(AgentOutputTypes.UI_PROPOSAL, { ...base, summary: 'UI/UX structure and brand direction plan drafted.' });
  if (agentId === 'alphonso') return createAgentOutput(AgentOutputTypes.CODE_PROPOSAL, { ...base, summary: 'Implementation plan + build/test verification checklist prepared.' });
  if (agentId === 'marcus') return createAgentOutput(AgentOutputTypes.AUDIT_REPORT, { ...base, summary: 'Audit checklist and release risk review drafted.' });
  return createAgentOutput(AgentOutputTypes.AGENT_TASK_PACKET, { ...base, summary: 'Generic agent packet output.' });
}

export function runAgentTask(agentId, taskPacket, projectName = 'project') {
  const traceId = taskPacket.traceId || `workflow-${Date.now()}`;
  appendTraceEvent({
    traceId,
    stage: 'task',
    generatedBy: 'jose',
    reason: `Task routed to ${agentId}`,
    inputSnapshot: taskPacket,
    approvalState: taskPacket.requiresApproval ? 'pending' : 'not_required',
    verificationState: 'unverified'
  });
  const output = deterministicAgentTemplate(agentId, taskPacket, projectName);
  const proposal = createDiffProposal({
    traceId,
    agentId,
    title: output.title,
    summary: output.summary,
    proposedDiffs: [
      {
        file: `proposals/${agentId}/${taskPacket.id}.md`,
        changeType: 'proposed_patch',
        diffText: `+ ${output.summary}\n+ risk: ${output.riskLevel}\n+ requiresApproval: ${output.requiresApproval}`
      }
    ],
    relatedFiles: output.relatedFiles || [],
    requiresApproval: output.requiresApproval
  });
  appendTraceEvent({
    traceId,
    stage: 'proposal',
    generatedBy: agentId,
    reason: 'Deterministic proposal generated.',
    inputSnapshot: { taskPacketId: taskPacket.id },
    proposedFileChanges: proposal.proposedDiffs,
    approvalState: output.requiresApproval ? 'pending' : 'not_required',
    verificationState: 'unverified',
    executionResult: 'not_executed'
  });
  return { ...output, traceId, proposalId: proposal.id };
}

export function collectAgentOutputs(outputs) {
  return outputs.filter(Boolean);
}

export function synthesizeAgentOutputs(outputs) {
  const byAgent = outputs.reduce((acc, output) => {
    const key = output.agentId || 'unknown';
    acc[key] = acc[key] || [];
    acc[key].push(output);
    return acc;
  }, {});
  return {
    totalOutputs: outputs.length,
    byAgent,
    highRiskCount: outputs.filter((output) => output.riskLevel === 'high' || output.riskLevel === 'critical').length
  };
}

export function createFinalExecutionPacket(project, outputs, approvalGates, sequence) {
  const synthesis = synthesizeAgentOutputs(outputs);
  return createAgentOutput(AgentOutputTypes.PROJECT_BREAKDOWN, {
    agentId: 'jose',
    projectId: project.id,
    title: `${project.projectName} Final Execution Packet`,
    summary: `Jose merged ${synthesis.totalOutputs} outputs with ${approvalGates.length} approval gates.`,
    status: 'ready',
    confidence: 'inferred',
    riskLevel: synthesis.highRiskCount > 0 ? 'high' : 'medium',
    assumptions: ['Final packet synthesized locally'],
    verifiedFacts: [`Outputs merged: ${synthesis.totalOutputs}`, `Approval gates: ${approvalGates.length}`],
    openQuestions: ['Confirm execution order', 'Confirm connector readiness for external actions'],
    recommendedNextSteps: ['Approve execution packet', 'Start first approved implementation milestone'],
    requiresApproval: true,
    relatedFiles: [],
    proposedChanges: [
      { kind: 'sequence', value: sequence },
      { kind: 'gates', value: approvalGates },
      { kind: 'outputs', value: synthesis.byAgent }
    ]
  });
}

export function runProjectWorkshop(projectInput) {
  const traceId = `workflow-${Date.now()}`;
  const project = receiveProjectIntake(projectInput);
  appendTraceEvent({
    traceId,
    stage: 'message',
    generatedBy: 'user',
    reason: 'Project brief intake',
    inputSnapshot: projectInput,
    approvalState: 'pending',
    verificationState: 'unverified'
  });
  const packets = routeProjectTasks(project);
  const enrichedPackets = packets.map((packet) => ({ ...packet, traceId }));
  const outputs = enrichedPackets.map((packet) => runAgentTask((packet.title.split(' task: ')[0] || '').toLowerCase(), packet, project.projectName));
  const collected = collectAgentOutputs(outputs);
  const sequence = produceExecutionSequence(project);
  const approvalGates = produceApprovalGates(project);
  const tasksByAgent = enrichedPackets.reduce((acc, packet) => {
    const id = (packet.title.split(' task: ')[0] || '').toLowerCase();
    acc[id] = acc[id] || [];
    acc[id].push(packet);
    return acc;
  }, {});
  const projectDna = createProjectDNA({
    projectId: project.id,
    architecture: 'modular multi-agent orchestration with approval gates',
    codingStandards: 'diff-first, traceable, reliability over impressiveness',
    stack: project.stack,
    deploymentModel: 'approval-gated local-first release flow',
    namingConventions: 'agent/service/panel explicit naming',
    businessGoals: project.projectDescription || 'execution reliability',
    designLanguage: 'dark premium calm operational UI',
    constraints: project.constraints || [],
    securityRules: ['read-only by default', 'approval required for risky actions', 'no secret exposure'],
    relevantFilesByAgent: {
      jose: ['src/services/agentWorkshop', 'src/services/projectExecution'],
      alphonso: ['src/services', 'src/components'],
      miya: ['src/components', 'src/assets'],
      hector: ['src/services/research', 'src/components/research'],
      marcus: ['src/services/audit', 'src/services/approval'],
      maria: ['src/services/projectExecution', 'src/components/projectExecution']
    },
    memoryHints: ['Use project_memory + decision_memory first', 'Prefer scoped context only']
  });
  const scopedContexts = buildAgentScopedContexts({
    traceId,
    projectId: project.id,
    tasksByAgent,
    projectDna
  });
  const workContracts = Object.entries(tasksByAgent).map(([agentId, tasks]) => createWorkContractDraft({
    traceId,
    projectId: project.id,
    draftedBy: 'jose',
    objective: `Complete ${agentId} assigned tasks for ${project.projectName}.`,
    allowedScope: ['analysis', 'proposal generation', 'scoped planning', 'task packet updates'],
    forbiddenScope: ['unsupervised file deletion', 'secret exposure', 'external posting without approval'],
    expectedOutput: `${agentId} output packet + trace + diff proposal`,
    riskLevel: tasks.some((task) => task.requiresApproval) ? 'high' : 'medium',
    validationRequirements: ['trace event present', 'proposal diff present', 'approval gate honored'],
    rollbackExpectations: ['revert proposal status', 'archive contract', 'record failure memory if blocked']
  }));
  const approvalRequests = approvalGates.map((gate) => createApprovalRequest({
    actionType: gate.actionType,
    riskLevel: gate.riskLevel,
    summary: gate.reason,
    metadata: { projectId: project.id, traceId, gateId: gate.id }
  }));
  appendTraceEvent({
    traceId,
    stage: 'approval',
    generatedBy: 'jose',
    reason: 'Approval requests created for execution gates.',
    inputSnapshot: approvalRequests.map((item) => ({ id: item.id, actionType: item.actionType })),
    approvalState: 'pending',
    verificationState: 'unverified'
  });
  const coordinationReport = createJoseCoordinationReport(project, packets);
  const finalPacket = createFinalExecutionPacket(project, collected, approvalGates, sequence);
  const verificationChain = createDefaultCrossVerificationChain({ traceId, projectId: project.id });
  const mode = getAgentMode();
  const executionState = getExecutionApprovalState();
  const executionGate = canExecuteAction(executionState);
  const aiReviewGate = evaluateAiReviewRequirement({
    hasHumanReview: Boolean(executionState.approved),
    runtimeValidated: Boolean(executionState.verified),
    buildVerified: Boolean(executionState.dependenciesChecked)
  });

  if (mode === AGENT_MODES.EXECUTION && !executionGate.ok) {
    addFailureMemory({
      projectId: project.id,
      agentId: 'jose',
      title: 'Execution blocked by governance gates',
      failureType: 'execution_blocked',
      message: executionGate.reason,
      source: 'agent_runner'
    });
    appendTraceEvent({
      traceId,
      stage: 'execution',
      generatedBy: 'jose',
      reason: executionGate.reason,
      approvalState: 'pending',
      verificationState: 'failed',
      executionResult: 'failed'
    });
  } else {
    appendTraceEvent({
      traceId,
      stage: 'execution',
      generatedBy: 'jose',
      reason: mode === AGENT_MODES.PROPOSAL ? 'Proposal mode (read-only default).' : 'Execution gate checks passed.',
      approvalState: executionState.approved ? 'approved' : 'pending',
      verificationState: mode === AGENT_MODES.PROPOSAL ? 'unverified' : 'verified',
      executionResult: mode === AGENT_MODES.PROPOSAL ? 'not_executed' : 'executed'
    });
  }
  if (!aiReviewGate.passes) {
    addFailureMemory({
      projectId: project.id,
      agentId: 'marcus',
      title: 'AI review gate blocked merge',
      failureType: 'ai_review_required',
      message: aiReviewGate.blockers.join(' '),
      source: 'ai_review_policy'
    });
  }
  appendTraceEvent({
    traceId,
    stage: 'verification',
    generatedBy: 'alphonso',
    reason: 'Workshop packet synthesized; awaiting runtime verification receipts.',
    approvalState: executionState.approved ? 'approved' : 'pending',
    verificationState: 'inferred',
    executionResult: 'partial'
  });
  addMemoryItem({
    type: 'decision_memory',
    projectId: project.id,
    agentId: 'jose',
    title: `${project.projectName} workshop trace recorded`,
    content: { traceId, mode, outputCount: collected.length, approvalRequestCount: approvalRequests.length },
    confidence: 'inferred',
    source: 'agent_runner',
    tags: ['traceability', 'workshop']
  });
  appendTraceEvent({
    traceId,
    stage: 'memory',
    generatedBy: 'echo',
    reason: 'Workshop decision memory persisted.',
    approvalState: executionState.approved ? 'approved' : 'pending',
    verificationState: 'inferred',
    executionResult: 'executed'
  });

  return {
    project,
    traceId,
    mode,
    packets: enrichedPackets,
    outputs: collected,
    sequence,
    approvalGates,
    approvalRequests,
    workContracts,
    verificationChain,
    scopedContexts,
    projectDna,
    aiReviewGate,
    coordinationReport,
    finalPacket
  };
}
