import { createAgentOutput, AgentOutputTypes } from '../../agents/shared/agentOutputSchemas';
import { assignTasksToAgents, createProjectExecutionPlan } from '../projectExecution/projectExecutionService';

function taskPacket(agentId, projectId, title, details, dependencyIds = []) {
  return createAgentOutput(AgentOutputTypes.AGENT_TASK_PACKET, {
    agentId: 'jose',
    projectId,
    title: `${agentId.toUpperCase()} task: ${title}`,
    summary: details,
    status: 'queued',
    confidence: 'inferred',
    riskLevel: /payout|publish|payment|deploy|upload/i.test(`${title} ${details}`) ? 'high' : 'medium',
    assumptions: ['Generated by deterministic routing matrix'],
    verifiedFacts: [],
    openQuestions: [],
    recommendedNextSteps: [`${agentId} to produce first draft output.`],
    requiresApproval: /payment|publish|deploy|upload|external/i.test(`${title} ${details}`),
    relatedFiles: [],
    proposedChanges: [{ kind: 'task_packet', dependencyIds }]
  });
}

export function receiveProjectIntake(projectInput) {
  return createProjectExecutionPlan(projectInput);
}

export function produceExecutionSequence(project) {
  return [
    { step: 1, owner: 'maria', action: 'requirements + roadmap', dependency: null },
    { step: 2, owner: 'hector', action: 'research checklist + source needs', dependency: 1 },
    { step: 3, owner: 'miya', action: 'ui/ux + brand + structure', dependency: 1 },
    { step: 4, owner: 'alphonso', action: 'implementation + build verification plan', dependency: [1, 2, 3] },
    { step: 5, owner: 'marcus', action: 'audit + security + readiness gate', dependency: [2, 4] },
    { step: 6, owner: 'jose', action: 'merge + confirm + final execution packet', dependency: [1, 2, 3, 4, 5] }
  ].map((item) => ({ ...item, projectId: project.id }));
}

export function produceApprovalGates(project) {
  return [
    { id: 'gate-file-write', actionType: 'file_write', riskLevel: 'high', reason: 'Prevent unsupervised code writes.' },
    { id: 'gate-external-api', actionType: 'external_api_connection', riskLevel: 'high', reason: 'Require explicit connector approval.' },
    { id: 'gate-payout', actionType: 'payout_payment_action', riskLevel: 'critical', reason: 'Payment and fraud risk requires manual approval.' },
    { id: 'gate-deploy', actionType: 'deployment', riskLevel: 'critical', reason: 'Production deployment requires explicit approval.' }
  ].map((item) => ({ ...item, projectId: project.id, status: 'pending' }));
}

export function routeProjectTasks(project) {
  const matrix = assignTasksToAgents(project);
  const packets = [];
  Object.entries(matrix).forEach(([agentId, tasks]) => {
    tasks.forEach((title, index) => {
      packets.push(taskPacket(agentId, project.id, title, `Deliverable ${index + 1} for ${project.projectName}.`));
    });
  });
  return packets;
}

export function createJoseCoordinationReport(project, packets) {
  return createAgentOutput(AgentOutputTypes.PROJECT_BREAKDOWN, {
    agentId: 'jose',
    projectId: project.id,
    title: `${project.projectName} orchestration summary`,
    summary: `Jose routed ${packets.length} packets across Maria, Hector, Miya, Alphonso, and Marcus.`,
    status: 'ready',
    confidence: 'inferred',
    riskLevel: 'medium',
    assumptions: ['Task outputs generated locally from deterministic templates'],
    verifiedFacts: ['Project intake captured', `Routed packet count: ${packets.length}`],
    openQuestions: ['Which packets should execute first?', 'Which connectors are configured for live actions?'],
    recommendedNextSteps: ['Review approval gates', 'Run agent workshop', 'Approve first execution sequence'],
    requiresApproval: false,
    relatedFiles: [],
    proposedChanges: []
  });
}

