import { describe, it, expect } from 'vitest';
import {
  PACKET_SCOPE, SESSION_EVENT_SCOPE, JOSE_COMMAND_SCOPE,
  GOVERNANCE_SCOPE, ORCHESTRATION_RECEIPT_SCOPE, ORCHESTRATION_QUEUE_SCOPE,
  VERIFICATION_SCOPE, CONNECTOR_SCOPE, CONNECTOR_AUDIT_SCOPE,
  CONNECTOR_AUTH_SCOPE, MIYA_MEMORY_SCOPE, PLUGINS_SCOPE,
  PLUGIN_AUDIT_SCOPE, PRODUCTION_READINESS_SCOPE, REPO_AUDIT_SCOPE,
  SELF_DEVELOPMENT_SCOPE, DEV_PACKET_SCOPE, TOOL_CONNECTION_SCOPE,
  TOOL_CONNECTION_AUDIT_SCOPE, WORKFLOW_OPS_SCOPE, WORKFLOW_RUN_SCOPE,
  WORKFLOW_RECEIPT_SCOPE, WORKFLOW_TELEMETRY_SCOPE, AGENT_OUTPUT_SCOPE,
  NOVA_SCORE_SCOPE, PROOF_AUTHORITY
} from '../../services/serviceScopes';

describe('serviceScopes', () => {
  it('exports all 26 scope constants', () => {
    expect(typeof PACKET_SCOPE).toBe('string');
    expect(typeof SESSION_EVENT_SCOPE).toBe('string');
    expect(typeof JOSE_COMMAND_SCOPE).toBe('string');
    expect(typeof GOVERNANCE_SCOPE).toBe('string');
    expect(typeof ORCHESTRATION_RECEIPT_SCOPE).toBe('string');
    expect(typeof ORCHESTRATION_QUEUE_SCOPE).toBe('string');
    expect(typeof VERIFICATION_SCOPE).toBe('string');
    expect(typeof CONNECTOR_SCOPE).toBe('string');
    expect(typeof CONNECTOR_AUDIT_SCOPE).toBe('string');
    expect(typeof CONNECTOR_AUTH_SCOPE).toBe('string');
    expect(typeof MIYA_MEMORY_SCOPE).toBe('string');
    expect(typeof PLUGINS_SCOPE).toBe('string');
    expect(typeof PLUGIN_AUDIT_SCOPE).toBe('string');
    expect(typeof PRODUCTION_READINESS_SCOPE).toBe('string');
    expect(typeof REPO_AUDIT_SCOPE).toBe('string');
    expect(typeof SELF_DEVELOPMENT_SCOPE).toBe('string');
    expect(typeof DEV_PACKET_SCOPE).toBe('string');
    expect(typeof TOOL_CONNECTION_SCOPE).toBe('string');
    expect(typeof TOOL_CONNECTION_AUDIT_SCOPE).toBe('string');
    expect(typeof WORKFLOW_OPS_SCOPE).toBe('string');
    expect(typeof WORKFLOW_RUN_SCOPE).toBe('string');
    expect(typeof WORKFLOW_RECEIPT_SCOPE).toBe('string');
    expect(typeof WORKFLOW_TELEMETRY_SCOPE).toBe('string');
    expect(typeof AGENT_OUTPUT_SCOPE).toBe('string');
    expect(typeof NOVA_SCORE_SCOPE).toBe('string');
    expect(typeof PROOF_AUTHORITY).toBe('object');
  });

  it('each scope is a non-empty string (or object for PROOF_AUTHORITY)', () => {
    const scopes = [
      PACKET_SCOPE, SESSION_EVENT_SCOPE, JOSE_COMMAND_SCOPE,
      GOVERNANCE_SCOPE, ORCHESTRATION_RECEIPT_SCOPE, ORCHESTRATION_QUEUE_SCOPE,
      VERIFICATION_SCOPE, CONNECTOR_SCOPE, CONNECTOR_AUDIT_SCOPE,
      CONNECTOR_AUTH_SCOPE, MIYA_MEMORY_SCOPE, PLUGINS_SCOPE,
      PLUGIN_AUDIT_SCOPE, PRODUCTION_READINESS_SCOPE, REPO_AUDIT_SCOPE,
      SELF_DEVELOPMENT_SCOPE, DEV_PACKET_SCOPE, TOOL_CONNECTION_SCOPE,
      TOOL_CONNECTION_AUDIT_SCOPE, WORKFLOW_OPS_SCOPE, WORKFLOW_RUN_SCOPE,
      WORKFLOW_RECEIPT_SCOPE, WORKFLOW_TELEMETRY_SCOPE, AGENT_OUTPUT_SCOPE,
      NOVA_SCORE_SCOPE
    ];
    scopes.forEach(s => expect(s.length).toBeGreaterThan(0));
  });

  it('scope strings end with _vN version suffix', () => {
    const versioned = [
      PACKET_SCOPE, SESSION_EVENT_SCOPE, JOSE_COMMAND_SCOPE,
      GOVERNANCE_SCOPE, ORCHESTRATION_RECEIPT_SCOPE, ORCHESTRATION_QUEUE_SCOPE,
      VERIFICATION_SCOPE, CONNECTOR_SCOPE, CONNECTOR_AUDIT_SCOPE,
      CONNECTOR_AUTH_SCOPE, MIYA_MEMORY_SCOPE, PLUGINS_SCOPE,
      PLUGIN_AUDIT_SCOPE, PRODUCTION_READINESS_SCOPE, REPO_AUDIT_SCOPE,
      SELF_DEVELOPMENT_SCOPE, DEV_PACKET_SCOPE, TOOL_CONNECTION_SCOPE,
      TOOL_CONNECTION_AUDIT_SCOPE, WORKFLOW_OPS_SCOPE, WORKFLOW_RUN_SCOPE,
      WORKFLOW_RECEIPT_SCOPE, WORKFLOW_TELEMETRY_SCOPE, AGENT_OUTPUT_SCOPE,
      NOVA_SCORE_SCOPE
    ];
    versioned.forEach(s => expect(s).toMatch(/_v\d+$/));
  });

  it('PROOF_AUTHORITY has RUST_ENGINE and JS_BRIDGE', () => {
    expect(PROOF_AUTHORITY.RUST_ENGINE).toBe('rust_engine');
    expect(PROOF_AUTHORITY.JS_BRIDGE).toBe('js_bridge');
  });

  it('scope values are unique', () => {
    const scopes = [
      PACKET_SCOPE, SESSION_EVENT_SCOPE, JOSE_COMMAND_SCOPE,
      GOVERNANCE_SCOPE, ORCHESTRATION_RECEIPT_SCOPE, ORCHESTRATION_QUEUE_SCOPE,
      VERIFICATION_SCOPE, CONNECTOR_SCOPE, CONNECTOR_AUDIT_SCOPE,
      CONNECTOR_AUTH_SCOPE, MIYA_MEMORY_SCOPE, PLUGINS_SCOPE,
      PLUGIN_AUDIT_SCOPE, PRODUCTION_READINESS_SCOPE, REPO_AUDIT_SCOPE,
      SELF_DEVELOPMENT_SCOPE, DEV_PACKET_SCOPE, TOOL_CONNECTION_SCOPE,
      TOOL_CONNECTION_AUDIT_SCOPE, WORKFLOW_OPS_SCOPE, WORKFLOW_RUN_SCOPE,
      WORKFLOW_RECEIPT_SCOPE, WORKFLOW_TELEMETRY_SCOPE, AGENT_OUTPUT_SCOPE,
      NOVA_SCORE_SCOPE
    ];
    expect(new Set(scopes).size).toBe(scopes.length);
  });
});
